# Versão do docker compose
version: "3.8"
# services --> define os containers que serão criados
services:
  samba-ad:
    image: samba4ad/samba-ad-dc:latest
    container_name: samba-ad
    hostname: ad.lab.local
    # Nome do dominio
    domainname: lab.local
    # environment --> define variáveis de ambite necessárias para configurar o domínio
    environment:
      - DOMAIN=LAB.LOCAL
      - DOMAINPASS=Admin@123
    # Expõe portas para o funcionamento do Active Directory.
    ports:
      - "53:53"
      - "88:88"
      - "135:135"
      - "137-138:137-138/udp"
      - "139:139"
      - "389:389"
      - "445:445"
      - "464:464"
      - "636:636"
      - "3268-3269:3268-3269"
    restart: always
    # Usa um volume persistente chamado samba-data para armazenar os dados do Samba
    volumes:
      - samba-data:/var/lib/samba
      # Coloca esse serviço na rede chamada jenkinsnet, permitindo que ele se comunique com outros containers
    networks:
      - jenkinsnet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    # Também está na rede jenkinsnet para se comunicar com o samba-ad.
    networks:
      - jenkinsnet
    restart: always
    # Garrante que o container samba-ad seja iniciado antes do Jenkins
    depends_on:
      - samba-ad

# Define dois volumes persistentes
volumes:
  samba-data:
  jenkins_home:

# Define uma rede Docker do tipo bridge chamada jenkinsnet, permite a comunicação entre os dois containers sem expor tudo para a rede externa.
networks:
  jenkinsnet:
    driver: bridge
