version: "3.8"

services:
  samba-ad:
    image: samba4ad/samba-ad-dc:latest
    container_name: samba-ad
    hostname: ad.lab.local
    domainname: lab.local
    environment:
      - DOMAIN=LAB.LOCAL
      - DOMAINPASS=Admin@123
    ports:
      - "53:53"
      - "88:88"
      - "135:135"
      - "137-138:137-138/udp"
      - "139:139"
      - "389:389"
      - "445:445"
      - "464:464"
      - "636:636"
      - "3268-3269:3268-3269"
    volumes:
      - samba-data:/var/lib/samba
    networks:
      - jenkinsnet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkinsnet
    depends_on:
      - samba-ad

volumes:
  samba-data:
  jenkins_home:

networks:
  jenkinsnet:
    driver: bridge
